### ISSUE TITLE
Why build mmyolo rather than integrate yolo models into mmdet?

### ISSUE THREAD

**Issue by likyoo** [open-mmlab/mmyolo#64]
Great work! 👍

**Comment by likyoo** [comment]
aha ~~~ :satisfied:

**Comment by mchaniotakis** [comment]
Both yolo models (v5, v7) are under GPL 3.0 license in their repos, however this repo is also under GPL 3.0 license. Looking at the rest of openmmlab's projects, they are all under apache license. Since these models are build form the ground up, why not just also use apache license for this repo as well?
